AdnanHodzic/displaylink-debian

README.md, displaylink-debian.sh
Added dependency checks and some hand-holding to install missing 
dependencies after confirming we're not on RedHat (because we don't 
need tools to confirm that and wouldn't have dpkg/apt if we were) and 
before we figure out if we're on Debian or Ubuntu (because we need
lsb-release for that).
=> Add dependency checks

post-install-guide.md
Upstream has changed the name of the systemd service from `displaylink` to `dlm`.  The tests explained here work fine if you substitute `dlm.service` for `displaylink.service`.  You can see the new file name in the `add_systemd_service()` function in `1.2.58/displaylink-driver-1.2.58/displaylink-installer.sh` starting on line 112.
rcw@antec:~/Projects/displaylink-debian/1.2.58/displaylink-driver-1.2.58$ systemctl status displaylink.service
Unit displaylink.service could not be found.
rcw@antec:~/Projects/displaylink-debian/1.2.58/displaylink-driver-1.2.58$ systemctl status dlm.service
● dlm.service - DisplayLink Manager Service
Loaded: loaded (/lib/systemd/system/dlm.service; static; vendor preset: enabled)
Active: active (running) since Sat 2016-10-15 06:33:22 PDT; 12min ago
Process: …
=> Upstream service name change

README.md
Two patches to the README, possibly only one of them are of interest to you.
1. Fix broken markdown syntax for upstream link
2. Refactor
The second one is probably easier to [review in my fork](https://github.com/troglobit/displaylink-debian/blob/master/README.md) ...
Cheers, and thank you for your awesome work on this! :smiley:
=> Fix link and refactor

displaylink-debian.sh
This is the needed changes to accommodate for the change in displaylink naming scheme, that  @aensley mentions in #92
=> Change to accommodate issue #92

displaylink-debian.sh
If a package has been removed, it might stay in status "uninstall".
Fixes #98
=> Verify install status of package

post-install-guide.md
Add troubleshooting section for "syntax error near unexpected token \`newline'"
Fixes #111, Fixes #102
Refs #89, Refs #65
=> Add troubleshooting section for "syntax error near unexpected token

displaylink-debian.sh
Since it seems it will take some time for the KERNEL_VERSION typo in evdi_connector.c https://github.com/DisplayLink/evdi/issues/117 has made it's way to the mainstream branch, I have made a small hack in your install script to make this change on the fly.
=> Change made to accommodate #114

displaylink-debian.sh
This change enables the displaylink-debian script
to be used in automated setups.
=> Add non-interactive operation

displaylink-debian.sh
Since the EVDI source has been corrected for the incorrect linux header reference I am removing the alteration part of the script.
This is done to make the script as clean as possible without any additinoal left overs from old compatibility hacks.
=> Removing alteration of EVDI source

displaylink-debian.sh
Tested on UEFI platform.
The downloaded installer got caught on whiptail console windows asking for approval/password for UEFI signage of docking station hardware.
(Which then of course were unavailable to me when running the installer-script contained in this repo, maybe that could be a future improvement)?
However, my workstation (Dell Latitude 5590) was already UEFI configured, so after completing the 4.2 installer by manual execution (without using the script in this repo), I was able to use my UEFI password to sign the hardware at next boot (with the hardware connected through boot).
I therefore submit/suggest Linux Mint 19 Tara be added to the list, seeing as I'm now connected to two screens through the docking station (Dell D6000). =)
=> Added Linux Mint Tara to supported platforms.

displaylink-debian.sh
User configuration files or configuration files installed by non-system packages should reside in /etc.
PS: thanks for your work!
=> Move 20-displaylink.conf to /etc

displaylink-debian.sh
This should fix #191 
It addresses the following issues:
* the patched evdi tar.gz needs to be flat (without subdirectories)
* uninstall of the dkms module didn't work anymore due to missing version. I'm using now the version from dkms. This should fix the problem `ERROR (code 2): Unable to add evdi/4.4.24 to DKMS source tree..` (the problem was, that evdi/4.4.24 already existed). Refs https://github.com/DisplayLink/evdi/issues/139#issuecomment-452641126
Improvements:
* Instead of patching two files (which might break in some time), I download the tar ball completely. We can use tagged versions (like v1.5.1) or branches (devel).
=> Use evdi 1.5.1 for new kernels

displaylink-debian.sh
The webpage https://www.displaylink.com/downloads/ubuntu has changed. The line with first occurrance of "download-link" doesn't contain the link anymore. This commit updates the grep to match the download link properly.
=> Fixed dlurl definition

evdi.sh
libelf-dev is required otherwise compilation fails on ubuntu 18.04 (and probably most debian based distros).
This gets hinted at in the official installer
error: Cannot generate ORC metadata for CONFIG_UNWINDER_ORC=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel
This causes Make to fail on your build too.
Tried on a fresh install of 18.04 with a kernel 5.4.6 and it makes it work.
=> adds libelf-dev

displaylink-debian.sh
Bug fix:
Removing older instance of $driver_dir during prep, so we can download latest...
=> Bug fix: Installation fails if a prior $driver_dir folder exists (cannot mkdir)

README.md
--------------- Linux system info ----------------
Distro: Ubuntu
Release: focal
Kernel: 5.4.0-28-generic
---------------- DisplayLink info ----------------
Driver version: 1.6.0+dfsg
5.2.14
DisplayLink service status: up and running
EVDI service version: 1.6.4
------------------ Graphics card -----------------
Vendor: i915
intel_ish_ipc
Subsystem: 615
Integrated
VGA: Intel Corporation UHD Graphics 615 (rev 02)
VGA (3D): 
X11 version: 1.20.8-2ubuntu2
X11 configs: /etc/X11/xorg.conf.d/20-displaylink.conf
-------------- DisplayLink xorg.conf -------------
File: /etc/X11/xorg.conf.d/20-displaylink.conf
Contents:
Section "OutputClass"
Identifier  "DisplayLink"
MatchDriver "evdi"
Driver      "modesetting"
Option      "AccelMethod" "none"
EndSection
-------------------- Monitors …
=> Update README.md: Ubuntu 20.04 Focal Fossa tested OK.

displaylink-debian.sh
When running the displaylink-debian.sh bash script, the following error is displayed:
/displaylink-debian.sh: line 99: syntax error near unexpected token `else'
Added `then` to elif to resolve error.
=> Fix syntax error near in displaylink-debian.sh

displaylink-debian.sh
Corrected paths so the error message "Invalid number of arguments passed." won't pop up on "Linux Mint 19.3 Cinnamon".
Can't estimate if that might break on other distributions.
=> fix for issue #413 'Invalid number of arguments passed.'

displaylink-debian.sh
This is to fix the following error message as outlined in https://github.com/AdnanHodzic/displaylink-debian/issues/431,
ln: failed to create symbolic link '/lib/modules/4.19.0-8-amd64/build/Kconfig': File exists
Note, this only fixes the issue if the file aleady exists, it will not fix a missing parent directory.
=> Overwrite existing destination file when creating build/Kconfig link.

displaylink-debian.sh, evdi.sh, resources/displaylink-installer.patch
This PR introduces fixes for these issues:
- Apparently displaylink-manager is expecting v1.7.0 instead of the latest v1.8.0.
Thanks to  AlainKnaff for finding the issue: https://github.com/AdnanHodzic/displaylink-debian/issues/451#issuecomment-670852323
- A proposed reboot from displaylink-installer.sh prevents displaylink-debian.sh to finish the install procedure and no conf file is generated. 
Thanks to rdmtinez for mentioning this https://github.com/AdnanHodzic/displaylink-debian/issues/430#issuecomment-671061085
=> Fix for wrong evdi version & conf creation bug

displaylink-debian.sh
Uninstall task stops process if /lib/modules/$(uname -r)/build/Kconfig doesn't exist.
=> Test if file exists

displaylink-debian.sh
Some users have reported that the output of  `lsb_release -is` was "Linuxmint" and others had "LinuxMint".
Closes #464
=> Perform case insensitive comparison of lsb_release for LinuxMint

README.md
Install procedure using git only. (The other wget method fails, and still requires git anyway). Fixes https://github.com/AdnanHodzic/displaylink-debian/issues/497
=> Update README.md (use git only, not wget)

displaylink-debian.sh
Because "set -e" in displaylink-debian.sh is set, also a grep with no output will stop the script.
I have a kvm without a VGA Card that has a usb3-PCIe card from the host system with a displaylink connected.
After the very small fix the displaylink-sdebian.sh script it worked.
Thank You for the good work.
=> make script work, if no VGA compatible controller is installed

displaylink-debian.sh
It looks like displaylink.com URLs started redirecting to synaptics.com, breaking the script.
This changes `displaylink-debian.sh` to work correctly with the Synaptics website.
Fixes #556.
=> Change download URLs to point to Synaptics website

displaylink-debian.sh
Some dual-card systems end up with `$drv` having values like
`"i915\nnvidia"`, and string equality fails for those cases. Use
bash wildcards instead to see if `$drv` contains `"nvidia"`.
fixes #596
=> improve nvidia detection for dual-card systems

README.md, displaylink-debian.sh
Debian Bullseye is now stable. Fixes script and readme accordingly.
Fixes #611
=> Debian Bookworm (testing) support

post-install-guide.md
On some distributions (at least Debian Bookworm/Sid) the sudo command does not preserve the user's environment, and thus the `-E` flag must be supplied to the sudo command. I created issue  #639 for this, where this solution can be found.
=> Added link to "Can't open display" error issue in the troubleshooting section

displaylink-debian.sh
This fixes the globbing pattern to match the filenames present in the v5.6.1 driver zip.
=> Fixes #738

displaylink-debian.sh
Add support for `kinetic`, which is due out in October.
`kinetic` will be using the 5.19 kernel, so makes sense to get that added
The output below shows that 1.12.0 of `evdi` works on 5.19, so should be all good
```
$ dkms status
evdi/1.12.0, 5.15.0-46-generic, x86_64: installed
evdi/1.12.0, 5.19.0-15-generic, x86_64: installed
```
Closes #745
=> Add kinetic and 5.19 support

displaylink-debian.sh
I made a small modification to add support for Parrot OS codename 'ara'. I was able to successfully get my DisplayLink monitor working. Please let me know if anything else is needed before these changes can be merged.
Here are my debug results:
```
--------------- Linux system info ----------------
Distro: Parrot
Release: ara
Kernel: 6.0.0-12parrot1-amd64
---------------- DisplayLink info ----------------
Driver version: 1.12.0
DisplayLink service status: up and running
EVDI service version: 1.12.0
------------------ Graphics card -----------------
Vendor: i915
Subsystem: [17aa:5078]
VGA: Intel Corporation CometLake-U GT2 [UHD Graphics] (rev 02)
VGA (3D): 
X11 version: 1.20.11-1+deb11u4
X11 configs: /etc/X11/xorg.conf.d/00-keyboard.conf /etc/X11/xorg.conf.d/20-displaylink.conf …
```
=> Added support for Parrot OS 5.1 (Electro Ara); Codename 'ara'

README.md, displaylink-debian.sh
Debian Bookworm is now stable. Fixes script and readme accordingly.
Fixes https://github.com/AdnanHodzic/displaylink-debian/issues/840
=> Debian Trixie (testing) support

README.md, displaylink-debian.sh
On my machine, running Ubuntu 23.10 Mantic, the script works as-is and I can use my dock. Hence, I’d suggest adding mantic to the list of supported codenames, and addressing bugs as they are found.
=> Support Ubuntu mantic

README.md, displaylink-debian.sh
- Removed "buster", which is a Debian release name
- Added "boron", which is the latest Bunsenlabs release name
=> Added latest Bunsenlabs (Debian 12) distro

displaylink-debian.sh
Otherwise dpkg -s foo will complain if there are multiple architectures of the library installed.
=> displaylink-debiah.sh: for -dev dependencies, explicitly specify the architecture

displaylink-debian.sh
We need dependency to build-essential to avoid the following error in the building step:
```
cc -I../module -std=gnu99 -fPIC -D_FILE_OFFSET_BITS=64  $(pkg-config --cflags-only-I libdrm)   -c -o evdi_lib.o evdi_lib.c
/bin/sh: 1: cc: not found
```
=> Add build-essential as dependancy

displaylink-debian.sh
This is a small patch to get an up-to-date evdi version during the install process, this allow kernel > 6.1 to work with displaylink.
Patch tried on Debian sid, kernel 6.6.
This should be removed once the kernel from synaptic got an up-to-date evdi version
=> Patch EVDI version for kernel > 6.1

README.md, displaylink-debian.sh
This PR removes the guards where we check for known distro releases. This should prevent breaking installs when a new distro release is installed.
=> refactor: remove guard for known distro releases

docs/post-install-guide.md
Presenting alternative, system-wide way of binding DisplayLink providers to the source.
This way the setting will be "persistent" after reboot.
=> doc: add alternative persistent provider source binding
