AdnanHodzic/displaylink-debian

README.md
displaylink-debian.sh

I added trusty and elementary support by allowing for upstart instead of systemd as the system init daemon

added trusty and elementary OS support

---

README.md
displaylink-debian.sh

Correct elementary OS Loki LSB info

---

displaylink-debian.sh

tested it only on a 4.9.2 debian kernel. maybe a detection has to be built in for older kernels using the packaged evdi kernel module

use different evdi kernel module from git repository to work on newer kernels (> 4.5 i guess)

---

displaylink-debian.sh

Support Ubuntu 17.04 Zesty

---

displaylink-debian.sh

Fixes #76 
Maybe the homepage layout was changed?
It should work now again, but it looks still very fragile...

Adjust download URL

---

displaylink-debian.sh

This fixes the download. The Software License Agreement needs to be accepted, before we can download the driver.
Finally fixes #76

Fix driver download

---

displaylink-debian.sh

Signed-off-by: Joachim Nilsson <troglobit@gmail.com>

Add support for Linux Mint Sonya

---

displaylink-debian.sh

I've tested this with a Dell DA100 displaylink adapter and the Juno beta (from http://developer.elementary.io) and can confirm it works.

Add support for elementary OS Juno

---

displaylink-debian.sh

Changed HTTP request to HTTPS protocol.

Change HTTP Requests to HTTPS for security.

---

displaylink-debian.sh

Make xorg_modesetting reachable.

Correct unreachable elif clause.

---

displaylink-debian.sh
displaylink-driver
displaylink.sh

Hello,
As the title suggests, the objective is to make the driver compatible with Devuan.  This is currently work in progress.

Devuan sysvinit cempatibility

---

displaylink-debian.sh
evdi.sh

Updates to allow this to work with Kernels 5.4
Tested on 
Distro: Kali Rolling 2020.1
Kernel: 5.4.0-kali3-amd64

Updating for build with 5.4 kernel

---

displaylink-debian.sh

I don't have a deep understanding of the code, but I attempted to fix the minor issues that popped up when I enabled "Bash Strict Mode".
- Closes #355

Use "Unofficial Bash Strict mode" and fix small issues identified with it.

---

README.md

Fixes the wget instructions in the README to solve #391

Update README to download additional scripts with wget

---

displaylink-debian.sh

This requires the whitelisting of PureOS, and the creation of
a Kconfig file to convince the installation script to proceed
(see https://adangel.org/2016/09/26/display-link-dell-intel-debian/ and
https://github.com/AdnanHodzic/displaylink-debian/issues/121)
Fixes https://github.com/AdnanHodzic/displaylink-debian/issues/121

Support PureOS

---

displaylink-debian.sh

Add support for Linuxmint Debbie

---

README.md
displaylink-debian.sh

Add support for Mint Ulyana

---

displaylink-debian.sh

Correct typo in Mint platform

---

displaylink-debian.sh

KDE Neon is an Ubuntu based distribution maintained by KDE https://neon.kde.org/
$ lsb_release -is
Neon
$ lsb_release -cs
focal

Add support for KDE Neon

---

displaylink-debian.sh

Add support for groovy, which I am already running, and the script works without a problem
Signed-off-by: Arif Ali <arif.ali@canonical.com>

Add groovy support

---

displaylink-debian.sh

Some small modifications:
- Refactor duplicate code
- Add pciutils as dependency (#486)
- Avoid error with cat if evdi was not installed correctly.
This prevented to run --debug

Merge changes

---

evdi.sh

Update to latest tagged release v1.7.1

---

README.md
displaylink-debian.sh

@AdnanHodzic  I hope you don't mind if I immediately merge minor changes like this.

Add support for Linux Mint 20.1

---

displaylink-debian.sh

lsb-release appears to return n/a on some Deepin versions
closes  #541

Add support for Deepin n/a

---

README.md
displaylink-debian.sh

First, thank you very much for developing the `displaylink-debian` and making it available.
I installed yesterday with the patched version and did not experience any adverse effects so far. If you would like the change to "cool off", I'm prepared to report my experiences again next week.
Thank you

add Ubuntu Hirsute to install requirements

---

README.md
displaylink-debian.sh

Add support for Nitrux

---

README.md
displaylink-debian.sh

Add support for Pop OS 21.04 hirsute

---

README.md
displaylink-debian.sh

Update supported platforms

---

README.md
displaylink-debian.sh

Perform case insensitive comparison for lsb Elementary
Add support for Elementary OS Odin

Add fixes for Elementary OS and Odin

---

README.md
displaylink-debian.sh

Add support for ZorinOS

---

displaylink-debian.sh

Fix reinstall issues

---

README.md
displaylink-debian.sh

Add support for Linux Mint 20.3 Una

---

displaylink-debian.sh
resources/displaylink-installer.patch

* Update max supported kernel
* Update regex for new version notation
* Update patch for new reboot logic

Add support for release 5.5

---

README.md
displaylink-debian.sh

Added Parrot OS 5+ Support

---

displaylink-debian.sh

I have tested on Debian Bookworm (testing) and everything is working.

Add support for kernel version 5.18

---

displaylink-debian.sh

fix: bunsenlabs string match

---

.gitignore
README.md
displaylink-debian.sh

 feat: add support for Linux Mint Vera 

---

README.md
post-install-guide.md

fix markdown
update some parts
closes #655 #742

doc: refactor docs

---

displaylink-debian.sh

I've added Linux Mint "victoria" to the list, installed the displaylink driver, and verified that it works (linux kernel 6.2.0-25-generic)

Support Linux Mint "victoria"

---

README.md
displaylink-debian.sh

Add support for Linux Mint 21.2 Victoria and LDME 6 Faye

---

displaylink-debian.sh

doc: update some bit.ly links

---

README.md
displaylink-debian.sh

Tested on Dell laptop with integrated Intel graphics and i-tec CADUAL4KDOCK docking station.
I had to remove file `/etc/X11/xorg.conf.d/20-displaylink.conf` to make it detect monitors.

Add support for Linux Mint 21.3 Virginia

---

README.md
displaylink-debian.sh

chore: add support for Parrot Lory

---

README.md
displaylink-debian.sh

chore: remove codename check for Zorin

---

README.md
displaylink-debian.sh

Closes #921
Tested this today and it's working in Ubuntu 24.04 with kernel 6.8.0-31-generic

feat: added support for ubuntu 24.04 noble numbat
